# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff9d0ed8595b01110c0d6aacd69e9191827b618f7b8b7d1cd0e7c58b0542856abeefaf3030f3a7ded08ac69a44385107ccf11f717a5171590fdba33e408588b8

test:
  secret_key_base: 68fd80966903e8c833a3bfa2bf01bc74ee22d65872fc2966817224b280d38f5736cc2000c394a10a6c26f0d24fae2efe5256d4aaa42a1fafbb224442c4971edf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
